In [66]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [67]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [68]:
from google.colab import files
Uploaded=files.upload()

Saving new.csv to new (1).csv


In [69]:
dataset= pd.read_csv('new.csv')
print(dataset)

     meanfreq        sd    median  ...  centroid   dfrange   label
0    0.059781  0.064241  0.032027  ...  0.059781  0.000000    male
1    0.066009  0.067310  0.040229  ...  0.066009  0.046875    male
2    0.077316       NaN  0.036718  ...  0.077316  0.007812    male
3    0.151228  0.072111  0.158011  ...  0.151228  0.554688    male
4    0.135120  0.079146  0.124656  ...  0.135120  5.476562    male
..        ...       ...       ...  ...       ...       ...     ...
623  0.131884  0.084734  0.153707  ...  0.131884  4.203125  female
624  0.116221  0.089221  0.076758  ...  0.116221  3.640625  female
625  0.142056  0.095798  0.183731  ...  0.142056  2.929688  female
626  0.143659  0.090628  0.184976  ...  0.143659  3.585938  female
627  0.165509  0.092884  0.183044  ...  0.165509  0.546875  female

[628 rows x 10 columns]


In [70]:
#Print Total number of Rows & columns in dataset
print(dataset.shape)

(628, 10)


In [71]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 628 entries, 0 to 627
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  628 non-null    float64
 1   sd        617 non-null    float64
 2   median    620 non-null    float64
 3   IQR       617 non-null    float64
 4   skew      615 non-null    float64
 5   kurt      617 non-null    float64
 6   mode      624 non-null    float64
 7   centroid  623 non-null    float64
 8   dfrange   628 non-null    float64
 9   label     628 non-null    object 
dtypes: float64(9), object(1)
memory usage: 49.2+ KB


In [81]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:9].values
# Extracting dependent variable:
y = dataset.iloc[:, 9].values

In [82]:
print(X)

[[0.05978099 0.06424127 0.03202691 ... 0.         0.05978099 0.        ]
 [0.06600874 0.06731003 0.04022874 ... 0.         0.06600874 0.046875  ]
 [0.0773155         nan 0.03671846 ... 0.         0.0773155  0.0078125 ]
 ...
 [0.14205626 0.09579843 0.18373124 ... 0.00800572 0.14205626 2.9296875 ]
 [0.14365875 0.09062826 0.18497617 ... 0.2122021  0.14365875 3.5859375 ]
 [0.16550895 0.09288354 0.18304392 ... 0.26770174 0.16550895 0.546875  ]]


In [83]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 0:8]) 
#Replacing missing data with the calculated mean value  
X[:, 0:8]= imputer.transform(X[:, 0:8])

In [85]:
dataframe=pd.DataFrame(X,columns=['meanfreq','sd','median','IQR', 'skew', 'kurt ', 'mode', 
                                  'centroid' ,'dfrange'])
dataframe.isnull().sum()

meanfreq    0
sd          0
median      0
IQR         0
skew        0
kurt        0
mode        0
centroid    0
dfrange     0
dtype: int64

In [87]:
from sklearn.preprocessing import LabelEncoder

number = LabelEncoder()
dataset['label']=number.fit_transform(dataset['label'].astype('str'))


In [88]:
print(X)

[[0.05978099 0.06424127 0.03202691 ... 0.         0.05978099 0.        ]
 [0.06600874 0.06731003 0.04022874 ... 0.         0.06600874 0.046875  ]
 [0.0773155  0.05647186 0.03671846 ... 0.         0.0773155  0.0078125 ]
 ...
 [0.14205626 0.09579843 0.18373124 ... 0.00800572 0.14205626 2.9296875 ]
 [0.14365875 0.09062826 0.18497617 ... 0.2122021  0.14365875 3.5859375 ]
 [0.16550895 0.09288354 0.18304392 ... 0.26770174 0.16550895 0.546875  ]]


In [90]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [91]:
print(X_train)

[[1.88623997e-01 3.87341050e-02 1.83567036e-01 ... 1.75301353e-01
  1.88623997e-01 3.46000000e+02]
 [2.30718823e-01 3.59190230e-02 2.38135048e-01 ... 2.43536977e-01
  2.30718823e-01 4.03000000e+02]
 [1.51228092e-01 7.21105870e-02 1.58011187e-01 ... 8.38781850e-02
  1.51228092e-01 4.70000000e+01]
 ...
 [1.87892751e-01 3.30672310e-02 1.87917784e-01 ... 1.93172475e-01
  1.87892751e-01 1.93000000e+02]
 [1.26194803e-01 8.45712970e-02 1.40900643e-01 ... 0.00000000e+00
  1.26194803e-01 3.30000000e+01]
 [1.53503740e-01 7.42933230e-02 1.72014995e-01 ... 1.56138710e-02
  1.53503740e-01 3.07000000e+02]]


In [92]:
print(X_test)

[[2.08305247e-01 4.39275580e-02 2.10193906e-01 ... 2.11357341e-01
  2.08305247e-01 3.24000000e+02]
 [2.12140714e-01 4.33291390e-02 2.12018209e-01 ... 2.06494689e-01
  2.12140714e-01 3.52000000e+02]
 [1.96006020e-01 5.39300620e-02 2.03383897e-01 ... 9.00116690e-02
  1.77549275e-01 2.10000000e+01]
 ...
 [1.76195335e-01 5.77743660e-02 1.70241546e-01 ... 1.70048309e-01
  1.76195335e-01 1.24000000e+02]
 [1.72729707e-01 6.38464710e-02 1.67575758e-01 ... 1.45656566e-01
  1.72729707e-01 1.15000000e+02]
 [2.29661337e-01 3.00959890e-02 2.31251360e-01 ... 2.30337323e-01
  2.29661337e-01 3.38000000e+02]]


In [93]:
print(y_test)

[0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 1 0 1 1 0 0 1
 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0
 0 0 1 1 0 0 0 0 0]


In [94]:
print(y_train)

[0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0
 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0
 1 0 1 1 0 1 0 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 1 0
 1 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1
 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 1 0 0 0 1 0
 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0
 0 0 1 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0
 0 0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0
 0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 1 0 1
 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0
 1 0 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0
 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1 1
 1 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1]


In [95]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [96]:
print(X_train)

[[ 0.3645598  -1.02230352  0.16201476 ...  0.43903798  0.35838062
   1.00752135]
 [ 1.59449156 -1.17860035  1.54587739 ...  1.32602852  1.59206532
   1.42288546]
 [-0.72807831  0.8307999  -0.48608994 ... -0.74936597 -0.7375915
  -1.17131842]
 ...
 [ 0.34319417 -1.33693536  0.27235115 ...  0.67134356  0.33694979
  -0.10740335]
 [-1.45950399  1.52263388 -0.92001893 ... -1.83969317 -1.47124902
  -1.27333767]
 [-0.66158815  0.9519881  -0.13094878 ... -1.63672945 -0.67089846
   0.72332486]]


In [97]:
print(X_test)

[[ 9.39608965e-01 -7.33956612e-01  8.37280892e-01 ...  9.07727479e-01
   9.35184453e-01  8.47205385e-01]
 [ 1.05167411e+00 -7.67181572e-01  8.83545812e-01 ...  8.44518175e-01
   1.04759154e+00  1.05124389e+00]
 [ 5.80248652e-01 -1.78605259e-01  6.64576835e-01 ... -6.69637200e-01
   3.38106805e-02 -1.36078275e+00]
 ...
 [ 1.41764305e-03  3.48352386e-02 -1.75924029e-01 ...  3.70753997e-01
  -5.86961094e-03 -6.10212523e-01]
 [-9.98414982e-02  3.71965994e-01 -2.43529285e-01 ...  5.36872797e-02
  -1.07437728e-01 -6.75796329e-01]
 [ 1.56359381e+00 -1.50190237e+00  1.37130481e+00 ...  1.15444706e+00
   1.56107328e+00  9.49224638e-01]]


In [98]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [99]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [100]:
print(y_pred)

[0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 1
 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 1 0
 0 0 1 1 1 0 0 0 0]


In [101]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[100  12]
 [  7  38]]


In [102]:
# calculate Accuracy
# calculate Accuracy
#   0   1
# 0[66  2(FP type 1)]
#1 [8(FN Type 24) 23]
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 87.90


In [103]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives) 
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/30
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.2f' % (precision))

Precision: 0.76


In [104]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 23/23+11
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall))

Recall: 0.844


In [105]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# (2*0.829*0.906)/0.829+0.906
# calculate score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

F-Measure: 80.000


In [106]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# (2*0.829*0.906)/0.829+0.906
# calculate score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

F-Measure: 80.000


In [107]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [108]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 87.90


In [109]:
# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0,probability=True)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=True, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [110]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [111]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 85.35


In [112]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[102  10]
 [ 13  32]]


In [113]:
# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 85.35


In [114]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives)
precision = precision_score(y_test, y_pred, average='binary')
print('Precision: %.3f' % (precision*100))

Precision: 76.190


In [115]:
# calculate recall
# Recall = TruePositives / (TruePositives + FalseNegatives)
recall = recall_score(y_test, y_pred, average='binary')
print('Recall: %.3f' % (recall*100))

Recall: 71.111


In [116]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# calculate score
score = f1_score(y_test, y_pred, average='binary')
print('F-Measure: %.3f' % (score*100))

F-Measure: 73.563


In [123]:
import pickle 
  
# Save the trained model as a pickle string. 
saved_model = pickle.dumps(classifier) 
  
# Load the pickled model 
model = pickle.loads(saved_model) 
  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0])

In [125]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/model.sav'
joblib.dump(classifier, filename)
 
# some time later...
 
# load the model from disk
randomforest_model = joblib.load(filename)
result = randomforest_model.score(X_test, y_test)
print(result)

0.8535031847133758


In [126]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/model.pkl', 'wb')) 
# Saving model to disk

[INFO] Saving model...


In [127]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/model.pkl', 'rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0])

In [128]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [129]:
!pip install streamlit

     |████████████████████████████████| 8.2MB 24.0MB/s 
     |████████████████████████████████| 4.2MB 34.9MB/s 
     |████████████████████████████████| 112kB 46.1MB/s 
     |████████████████████████████████| 163kB 51.0MB/s 
     |████████████████████████████████| 81kB 9.8MB/s 
     |████████████████████████████████| 122kB 56.5MB/s 
     |████████████████████████████████| 71kB 9.3MB/s 
  Created wheel for blinker: filename=blinker-1.4-cp37-none-any.whl size=13448 sha256=d15a14fc2bc705500eed5196465fa69eefd4da73cb12d5e303db1a81dd65521d
  Stored in directory: /root/.cache/pip/wheels/92/a0/00/8690a57883956a301d91cf4ec999cc0b258b01e3f548f86e89
Successfully built blinker
ERROR: google-colab 1.0.0 has requirement ipykernel~=4.10, but you'll have ipykernel 5.5.4 which is incompatible.
  Found existing installation: ipykernel 4.10.1
    Uninstalling ipykernel-4.10.1:
      Successfully uninstalled ipykernel-4.10.1


In [130]:
!pip install pyngrok

     |████████████████████████████████| 747kB 16.7MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.0.5-cp37-none-any.whl size=19246 sha256=11f174b3cd08a6d66d397f6c24735c5d0fa6607e9978d03066e12a7c903a5bc5
  Stored in directory: /root/.cache/pip/wheels/0c/13/64/5ebbcc22eaf53fdf5766b397c1fb17c83f5775fdccf0ea1b88
Successfully built pyngrok


In [161]:
!ngrok authtoken 1rh7vlXXZxc7RJ8rPFV1UzSbAdN_49pPNkGSrCEHw2GdRsNJp

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [163]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
model = pickle.load(open('/content/drive/My Drive/model.pkl', 'rb')) 
# Feature Scaling
dataset = pd.read_csv('/content/drive/My Drive/new.csv')
# Extracting independent variable:
X = dataset.iloc[:, [1,2,3]].values
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

def predict_note_authentication(meanfreq,sd,median,IQR,skew,kurt,mode,centroid,dfrange):
  output= model.predict(sc.transform([[meanfreq,sd,median,IQR,skew,kurt,mode,centroid,dfrange]]))
  print("voice belong to male or female", output)
  if output==[1]:
    prediction="female"
  else:
    prediction="male"
  print(prediction)
  return prediction
def main():
    
    html_temp = """
   <div class="" style="background-color:Brown;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:black;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:black;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:black;margin-top:10px;"Machine Learning Lab Experiment</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    st.header("voice belong to male or female prediction using logistic classification")
    
    
    meanfreq = st.number_input('Insert a meanfreq between 0 to 627')
    sd= st.number_input('Insert between 0 to 616 ')
    IQR = st.number_input('Insert between 0 - 619 ')
    skew = st.number_input('Insert between 0 - 614 ')
    kurt = st.number_input('Insert 0-617 ')
    mode = st.number_input('Insert 0-624')
    centroid = st.number_input('Insert0-622 ')
    dfrange= st.number_input('Insert Between 0 - 627 ')
    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(UserID, Gender1,Age,EstimatedSalary)
      st.success('Model has predicted {}'.format(result))
      
    if st.button("About"):
      st.subheader("Developed by PRAKHAR MEHRISHI")
      st.subheader("Head , Department of Computer Engineering")

    st.markdown(html_temp,unsafe_allow_html=True)
if __name__=='__main__':
  main()

Overwriting app.py


In [164]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [165]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url

<NgrokTunnel: "http://91eb1c3423a9.ngrok.io" -> "http://localhost:80">

In [ ]:
!streamlit run --server.port 80 app.py

2021-05-11 11:41:18.285 An update to the [server] config option section was detected. To have these changes be reflected, please restart streamlit.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://35.221.2.156:80

